version: '3'

services:

  mongo:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev

    ports:
      - 27017:27017

    volumes:
      - ./mongo:/var/lib/mongo